### ISSUE TITLE
Missing double quote

### ISSUE THREAD

**Issue by brusan** [devangshekhawat/Fedora-35-Post-Install-Guide#1]
Trivial, but I think the line glxinfo|egrep "OpenGL vendor|OpenGL renderer should have a closing double quote.

**Comment by devangshekhawat** [comment]
> Trivial, but I think the line glxinfo|egrep "OpenGL vendor|OpenGL renderer should have a closing double quote.

Ah, sorry my bad. Fixed it now! I also removed some other things like system76-power as it broke 2 of friends' systems and using prime is way more convenient.

**Comment by devangshekhawat** [comment]
Made some nice changes.
